### ISSUE TITLE
styles.css is invalid

### ISSUE THREAD

**Issue by dmromanov** [lexnekr/bitrix-template-whitesquare-bootstrap#1]
```
@brand-font;
```

```
&:before {
    content: '';
}
}
}
}
```

etc.

**Comment by lexnekr** [comment]
Спасибо!
                    &:before {
                        content: '';
                    }

Уберу. Уж и не помню откуда это взялось.

P.S. Вас не смущает, что это Bootsrap2 и слегка устарело всё уже?

**Comment by dmromanov** [comment]
@lexnekr 
Bootstrap 3:
whitesquare-bootstrap/css/bootstrap.css `Bootstrap v3.0.3`

А так всё более-менее работает.
Библиотеки использую свежие.

**Comment by lexnekr** [comment]
О, правда.
Прошу прощения, вчера решил, что правка пришла в другой репо, который так же давно не изменял.

Ещё раз спасибо - правка вчера внесена.
